# Generated by Django 2.1.4 on 2018-12-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='用户名')),
                ('email', models.EmailField(max_length=255, verbose_name='邮箱')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('registerDate', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('changeDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户账号',
                'verbose_name_plural': '用户账号',
            },
        ),
    ]
