# Generated by Django 2.1.4 on 2018-12-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0002_user_isactive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
