# Generated by Django 2.1.4 on 2018-12-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birth',
            field=models.DateField(default=None, verbose_name='出生日期'),
        ),
    ]
