# Generated by Django 2.1.4 on 2018-12-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0002_userinfo_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateField(default='2002-02-16', verbose_name='出生日期'),
        ),
    ]
