# Generated by Django 2.1.4 on 2018-12-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0005_auto_20181231_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateField(default=None, verbose_name='出生日期'),
        ),
    ]
