# Generated by Django 2.1.4 on 2018-12-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0008_auto_20181231_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateField(default='2018-12-31', verbose_name='出生日期'),
        ),
    ]
