# Generated by Django 2.1.4 on 2018-12-31 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0014_auto_20181231_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 31), null=True, verbose_name='出生日期'),
        ),
    ]
