# Generated by Django 2.1.8 on 2019-04-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0018_auto_20190427_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(max_length=100, verbose_name='金额')),
                ('datetime', models.DateField(default='2019-04-27', verbose_name='日期')),
            ],
        ),
    ]
