# Generated by Django 2.1.8 on 2019-04-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0019_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='article',
            field=models.CharField(max_length=11, null=True, verbose_name='项目'),
        ),
    ]
