# Generated by Django 2.1.8 on 2019-04-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0020_money_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='creatUser',
            field=models.CharField(max_length=100, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='money',
            name='article',
            field=models.CharField(max_length=111, null=True, verbose_name='项目'),
        ),
    ]
