# Generated by Django 2.1.8 on 2019-04-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0021_auto_20190427_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneyinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100, verbose_name='金额')),
                ('article', models.CharField(max_length=111, null=True, verbose_name='项目')),
                ('datetime', models.DateField(default='2019-04-27', verbose_name='日期')),
                ('creatUser', models.CharField(max_length=100, null=True, verbose_name='创建人')),
            ],
        ),
        migrations.DeleteModel(
            name='money',
        ),
    ]
