# Generated by Django 2.1.8 on 2019-04-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0022_auto_20190427_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moneyinfo',
            new_name='moneyin',
        ),
    ]
